### ISSUE TITLE
Error building handlebars-brunch on windows 10

### ISSUE THREAD

**Issue by alexmario74** [brunch/handlebars-brunch#43]
Launching the command:

npm install 

I got:

> handlebars-brunch@1.10.1 postinstall D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch
> node ./postinstall.js

fs.js:902
  return binding.symlink(preprocessSymlinkDestination(destination, type, path),
                 ^

Error: EPERM: operation not permitted, symlink 'D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\node_modules\handlebars\dist\handlebars.js' -> 'D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\dist\D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\dist\handlebars.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:902:18)
    at D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\postinstall.js:17:10
    at Array.forEach (native)
    at D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\postinstall.js:14:9
    at Array.forEach (native)
    at D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\postinstall.js:13:7
    at Array.forEach (native)
    at Object.<anonymous> (D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\postinstall.js:12:9)
    at Module._compile (module.js:434:26)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\tools\\node-4.1.2\\node.exe" "D:\\tools\\node-4.1.2\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! handlebars-brunch@1.10.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the handlebars-brunch@1.10.1 postinstall script 'node ./postinstall.js'.
npm ERR! This is most likely a problem with the handlebars-brunch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls handlebars-brunch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\npm-debug.log

**Comment by es128** [comment]
Try running as administrator. Should be a one-time thing for establishing the symlinks.

**Comment by alexmario74** [comment]
I'm running as Administrator:

PS D:\My\Path\...\handlebars-brunch> id
uid=500(mario) gid=544(Administrators) groups=544(Administrators)

**Comment by alexmario74** [comment]
Did you notice the target?

D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\dist\D:\WORK\MaxCorp\envs\redisNode\projects\handlebars-brunch\dist\handlebars.js

It's invalid path.
